version: "2"

jobs:
  build:
    docker: [{image: "docker:17.12.0-ce-git"}]
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build
        command: docker build -t velocitymob/pandocker:xxxxx-test-circleci-xxxxx .
    # - run:
    #     name: Test
    #     command: tests/test.sh xxxxx-test-circleci-xxxxx
